### ISSUE TITLE
Enhancement: Adding min_length to ArrayFilter

### ISSUE THREAD

**Issue by jwoertink** [cypriss/mutations#127]
The String filter already has this option. It would be awesome if this was added to Array.

```ruby
required do
  # Array is required, and must have a `length >= 2`
  array :items, min_length: 2
end
```

**Comment by eugeneius** [comment]
Sounds reasonable! Are you interested in writing a patch?

**Comment by jwoertink** [comment]
Sure, I can send a PR.
