### ISSUE TITLE
I can't pass a Hash to the mutation

### ISSUE THREAD

**Issue by Ahmunna** [cypriss/mutations#156]
I pass a hash to the mutation this way : 
``` 
DoSomething(var: my_hash)
```

In my DoSomething Class i have the following : 
```
optional do
  hash :var
end
```
When i try to work with var i get an empty hash
ps : my hash have a hash as a value

my gem version is the following:
gem 'mutations', '~> 0.8.2'

**Comment by eugeneius** [comment]
That's the intended behaviour - mutations inputs should be structured data, and an arbitrary hash is unstructured.

See https://github.com/cypriss/mutations/pull/44, https://github.com/cypriss/mutations/issues/63, and https://github.com/cypriss/mutations/pull/116 for previous discussions on this topic.

You can allow an arbitrary hash like this:

```ruby
model :var, class: Hash
```

Or alternatively:

```ruby
duck :var, methods: :to_hash
```

I do think something like https://github.com/cypriss/mutations/pull/44 would be clearer to read, though. Maybe we should reconsider adding it.
