### ISSUE TITLE
Validate hash with mixed required attributes

### ISSUE THREAD

**Issue by M-Hagras** [cypriss/mutations#162]
Is there a way to validate nested hash with attributes required and attributes optional ?

`params: {
    a: required,
    X: {
        'Y': required,
        'Z': optional
    },
    b: optional
}`

Something like
```
required do
    string :a
    hash :x do
      string :y
    end
  end

  optional do
    string :b
    hash :x do
      string :z
    end
   end
```

thanks

**Comment by eugeneius** [comment]
You can use `required` and `optional` blocks inside a hash filter:

```ruby
required do
  string :a

  hash :x do
    required do
      string :y
    end

    optional do
      string :z
    end
  end
end

optional do
  string :b
end
```

**Comment by M-Hagras** [comment]
@eugeneius Thanks 👍
