### ISSUE TITLE
support Time objects

### ISSUE THREAD

**Issue by assembler** [cypriss/mutations#54]
Changing following line:
https://github.com/cypriss/mutations/blob/master/lib/mutations/date_filter.rb#L20

to: 
`if data.is_a?(Date) || data.is_a?(Time)`

Would support both Date, DateTime and Time objects. I'm dealing with TimeWithZone instances in my rails project and this would come in handy. Up until then, I could use the following:

```
duck :starts_at, methods: [:acts_like_time?]
```

**Comment by lorcan** [comment]
I've added a PR that would support time objects: https://github.com/cypriss/mutations/pull/90

**Comment by eugeneius** [comment]
https://github.com/cypriss/mutations/pull/90 was released in 0.8.0! 🎉
