### ISSUE TITLE
Does Mutations need Maintainers?

### ISSUE THREAD

**Issue by ryanfaerman** [cypriss/mutations#80]
@cypriss I'm sure you're a very busy dude... do you need help maintaining this project?

There are growing number of pull requests and other issues that some people would love to be able to help get merged into the main branch.

Any chance of that happening?

**Comment by elfassy** [comment]
+1
last commit is from 6months ago.

**Comment by tfausak** [comment]
If you're looking for a better-maintained alternative, check out [ActiveInteraction](https://github.com/orgsync/active_interaction). I am one of the maintainers. We have hundreds of commits this year and released a new version this week. And for what it's worth, all of the open pull requests against Mutations already work in ActiveInteraction :smile:

**Comment by elfassy** [comment]
@tfausak is there a way to add validations to a nested filters values without writing a custom validation method? I think that's the only thing missing for me. Thanks

**Comment by tfausak** [comment]
I'm not entirely sure what you mean. Can you open an issue against ActiveInteraction to talk about it?
