### ISSUE TITLE
Bump version to 0.7.3 ?

### ISSUE THREAD

**Issue by alfredolopez-kantox** [cypriss/mutations#92]
I am using the latest version from rubygems but it seems it doesn't include the latest fixes (ie: https://github.com/cypriss/mutations/pull/86). When do you think it would be possible to have a new version of this gem?

**Comment by chrisgogreen** [comment]
Would be nice to have a tag for each version also.

**Comment by dmitry** [comment]
As I know bundler automatically adds tags to the github, once version is published to the rubygems.

**Comment by patrickod** [comment]
I just manually went through the gem's version history and have pushed tags for each version released on rubygems. I believe they should be accurate - if you find any issues with them please do let me know and I'll update the tags to point to the correct commit for a given version.

**Comment by patrickod** [comment]
As for a release I think merging #90 would be a nice addition and would bring us to a `0.8.0` release. I hope to have this done in the coming days.

**Comment by lorcan** [comment]
Now that #90 has been merged shall we bump to `0.8.0`?

**Comment by patrickod** [comment]
We have a `0.8.0` release now so closing out.
