### ISSUE TITLE
Boolean filter does not support value check

### ISSUE THREAD

**Issue by leonfu103** [cypriss/mutations#96]
I need to validate the value of a boolean before performing a mutation command.

I would like to return all the basic validation messages at once. For example if the username or password is missing and the terms and conditions have not been accepted I would like to return both messages at once.

Unfortunately the `BooleanFilter` only validates the presence of a boolean value, not that it is either `true` or `false.

I was able to check that the value is true using this method:

```ruby
class SignUpUser < Mutations::Command
  required do
    string :email
    string :password
    model :accept_terms_and_conditions, class: TrueClass
  end
end
```

Obviously using the `ModelFilter` and expecting it to be an (or more accurately, _the_) instance of `TrueClass` is not an expressive solution to my requirement.

I plan to propose a PR that allows me to express that the boolean should be true,

```ruby
module Mutations
  class SignUpUser < Mutations::Command
    required do
      string :email
      string :password
      boolean :accept_terms_and_conditions, expect: true
    end

    def execute
      # do stuff
    end
  end
end
```

**Comment by lorcan** [comment]
You should consider using the built-in validation https://github.com/cypriss/mutations#what-about-validation-errors, maybe something like this?

```
module Mutations
  class SignUpUser < Mutations::Command
    required do
      string :email
      string :password
      boolean :accept_terms_and_conditions
    end

    def validate
      add_error(:accept_terms_and_conditions, :invalid, 'You must accept the terms and conditions') unless accept_terms_and_conditions == true
    end

    def execute
      # do stuff
    end
  end
end
```
