### ISSUE TITLE
Offering help with maintainership

### ISSUE THREAD

**Issue by patrickod** [cypriss/mutations#97]
Hey there! 

Myself and my colleagues at [Intercom](https://www.intercom.io) are big fans and users of this gem, and wanted to thank you and all the contributors for your work. 

In the last few months we've built some monkeypatchsolutions to extend mutations in various ways, some of which we've opened as PRs: https://github.com/cypriss/mutations/pull/90, https://github.com/cypriss/mutations/pull/89. 

These and other changes live in our codebase as monkeypatches. We think they'd be beneficial to the wider community and we'd love to help get them merged into master and released. On top of that we'd like to offer our communal helping hands in maintaining and otherwise improving the gem.

So I wanted to open an issue to start a discussion about this, and to see if you would be open to some help in maintaining the codebase 😄

**Comment by cypriss** [comment]
@patrickod I'd love help (I'm obviously largely focused on other things now). The two PRs you sent are solid, and I'm a fan of intercom.

**Comment by cypriss** [comment]
Made you a collaborator. Is there some way I can give you access to push new versions to rubygems?

**Comment by patrickod** [comment]
Awesome! Thanks :smile: 

I think `gem owner -a p@trickod.com` **should** add me, going by the rubygems documentation [here](http://guides.rubygems.org/command-reference/#gem-owner).

**Comment by cypriss** [comment]
Done. It was ```gem owner mutations -a p@trickod.com``` btw.

Let me know if I can do anything else!
